use_frameworks!

platform :ios, '8.0'

target 'libSQLCipherDB_Example' do
  pod 'libSQLCipherDB', :path => '../'

  # pod 'FMDB/SQLCipher'

  # target 'libSQLCipherDB_Tests' do
  #   inherit! :search_paths
  #
  # end

end
