use_frameworks!

platform :ios, '8.0'

target 'LWSQLCipherDB_Example' do
  pod 'LWSQLCipherDB', :path => '../'

  pod 'SQLCipher'
  # pod 'FMDB/SQLCipher'

  # target 'LWSQLCipherDB_Tests' do
  #   inherit! :search_paths
  #
  # end

end
